version: '3'

services:
  database:
    image: mysql:latest
    container_name: stock-market-database
    environment:
      - MYSQL_DATABASE=stock-market
      #- MYSQL_USER=root
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev
    ports:
      - "3306:3306"
    networks:
      - stock-market-net

  php-fpm:
    container_name: stock-market-php
    build:
      context: .docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - .:/opt
    networks:
      - stock-market-net
#
  nginx:
    image: nginx:alpine
    container_name: stock-market-nginx
    volumes:
      - .:/opt
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    tty: true
    networks:
      - stock-market-net

  angular:
    container_name: stock-market-angular
    build:
      context: .
      dockerfile: .docker/angular/Dockerfile
    ports:
      - "8080:4200"
    depends_on:
      - php-fpm
    volumes:
      - ./frontend:/opt
    networks:
      - stock-market-net

networks:
  stock-market-net:
    driver: bridge
